### ISSUE TITLE
It doesn't run files according to the .scss-lint.yml

### ISSUE THREAD

**Issue by oddlyfunctional** [mmozuras/pronto-scss#1]
I'm trying to exclude a external library from the scss-lint analysis by adding the `exclude: 'path/to/lib/**/*'` option to the `.scss-lint.yml` file, and everything is fine when running `scss-lint .`, but when I run `pronto run` it keeps getting analysed. What should I do?

**Comment by mmozuras** [comment]
@mrodrigues seems like a bug, I'll see what can be done :smile:

**Comment by mmozuras** [comment]
Fixed and released as `v0.4.6` :smile:
