### ISSUE TITLE
Ruby sass will be completely unmaintained as of 26 March 2019

### ISSUE THREAD

**Issue by abinoam** [mmozuras/pronto-scss#10]
Pronto-scss depends on sccs-lint.
Scss-lint depends on ruby-sass
Ruby sass will be completely unmaintained as of 26 March 2019

See:
- Deprecation note at Ruby Sass Readme at https://github.com/sass/ruby-sass
- Deprecation note at Ruby Sass website https://sass-lang.com/ruby-sass
- Scss-lint will probably deprecate soon. See note at Readme file https://github.com/brigade/scss-lint
- Some discussion at Sass Rails repo https://github.com/rails/sass-rails/issues/420

As pronto need some hooks to do its job, I don't think there's a perfect substitute for scss-lint/ruby-sass. 😞 

The Rails scenario related to assets like scss/css changed a lot with webpack arrival. 

Any plan @mmozuras ?

**Comment by mmozuras** [comment]
@abinoam they are recommending using [stylelint](https://stylelint.io) or [sass-lint](https://github.com/sasstools/sass-lint) instead. We could have runners for both of them as alternatives. @kevinjalbert actually already wrote [one](https://github.com/kevinjalbert/pronto-stylelint) for stylelint. What do you think of them as alternatives?

**Comment by ashkulz** [comment]
I'm not sure there's anything much that can be done, tbh -- at the most, one can add a note in the README (PRs welcome!).
