### ISSUE TITLE
`scss_files` config option not respected

### ISSUE THREAD

**Issue by doits** [mmozuras/pronto-scss#4]
I have the following `.scss-lint.yml` in my directory:

```
scss_files: 'app/assets/stylesheets/**/*.scss'
```

When I run `scss-lint`, it correctly only lints the files in the `app/assets/stylesheets` directory and ignores others. But when I run `pronto run` (with changes of a scss file in a different directory), I get the error:

```
app/assets/icons/scss-rails-nolint.scss:14 E: Syntax Error: Invalid [...]
```

(the syntax error is correct for that file, because it only has the ending `.scss` and in fact is not a scss file, but therefore I do not want to lint it by using the above option.)

So it looks like the `scss_files` option is not respected.

**Comment by doits** [comment]
I gave it a shot at https://github.com/Stellenticket/scss-lint/commit/152d80f3ba7dff7975b4f7f415b9c2f704dcf8fc - what do you think about it?

**Comment by mmozuras** [comment]
@doits the code itself looks good :smile:. From my  point of view, it makes sense, but it's hard for me judge whether it makes sense for them :smile:.

**Comment by doits** [comment]
Who do you mean with "them"?

**Comment by mmozuras** [comment]
@doits [brigade](https://github.com/brigade), owners of [scss-lint](https://github.com/brigade/scss-lint).

**Comment by doits** [comment]
Ah sorry I totally messed it up and forked `scss-lint` instead of `pronto-scss`, added it as a remote in my fork of `pronto-scss` and pushed `pronto-scss` to `scss-lint` - whatever ;-) Sorry for the confusion.

It actually was a patch for `pronto-scss`. Now I refactored it to use `config.scss_files` from `scss-lint` so we do not need that ugly `fnmatch` function and pushed it to the correct repo, see pr #5.

**Comment by mmozuras** [comment]
@doits got it :smile:
