### ISSUE TITLE
Property order lints sometimes don't get reported

### ISSUE THREAD

**Issue by ibrahima** [mmozuras/pronto-scss#7]
Hi, firstly, thanks for pronto and all the runners!

I've recently discovered an issue in how pronto-scss handles SCSSLint::Linter::PropertySortOrder lints: because the lint can occur on a line that's not the one that caused the lint (eg. you can add a property that violates sort order to the end of the list, but the lint will go on the first line that's out of order, i.e. the line that the property should go on), pronto-scss often misses a bunch of lints because they're not marked on the line that caused them, so it thinks they're not part of the patch.

Here's an example using the SMACSS sort order:

```diff
.alert_two {
  font-size: $font-size-base;
  z-index: $z-index-alert;
+ text-align: center; # This line should be above z-index, but it won't be marked as a lint
}
```

Not sure if there's a way to even handle this easily without changes to scss-lint, or even if such a thing makes sense. scss-lint shouldn't know about patches so the fact that it puts the lint on the first line that's out of order makes sense. I guess the desired behavior is that if there's a PropertySortOrder lint, it should see if any lines in the diff are within the same block as the lint, and if so, it should pick the first line that's within the diff to comment on. I've been poking at the `lint.linter.engine.tree` object to try and figure out if we can determine the context of the lint easily, and then figure out if any lines within the patch are possibly the cause of the lint, but I think I need to eject from this rabbit hole for now before it consumes the rest of my day. I just wanted to report this and make a note of it so that people are aware that this is an issue, and so that I can fix it later if I get a chance.

**Comment by mmozuras** [comment]
There is a similar issue reported here: https://github.com/mmozuras/pronto/issues/220
I'll close this one and leave that one as the main one 🙂.
